### ISSUE TITLE
Supprimer un lieu de stockage

### ISSUE THREAD

**Issue by sfavot** [Gabite/MyCellar#11]
- [x] Ajouter une route pour supprimer un lieu de stockage
- [x] Les bouteilles rangées dans ce lieu prennent un lieu de stockage nul

**Comment by GabrielFavot** [comment]
Pourquoi mettre le lieu de stockage obligatoire ? Les bouteilles ne sont pas forcement rangées quelque part

On peut par contre marqué les bouteilles qui n'ont pas de lieu de stockage d'un label, pour signaler au caviste qu'il faut ranger ses affaires.

**Comment by sfavot** [comment]
okay 👍 
J'ai crée une carte pour faire une page "Bouteilles pas rangées"
